nBuryloAuthBundle_auth:
    resource: "@nBuryloAuthBundle/Controller/AuthController.php"
    type:     annotation

nBuryloAuthBundle_user:
    resource: "@nBuryloAuthBundle/Controller/UserController.php"
    type:     annotation
    
nBuryloAuthBundle_group:
    resource: "@nBuryloAuthBundle/Controller/GroupController.php"
    type:     annotation
    